sudo: false
language: generic
addons:
  apt:
    packages:
      - libgmp-dev
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
env:
  global:
    - HACKAGE_USERNAME=fozworth
    - secure: dyr1akAjxLyc4+4wHEGYfvyJpI5Ezcqj/KOO29MNQRDs+3FfTiq0rpB015xbxfawAH8PTrXn/f/NzxH7lR28X5NRDpC1IKG1G8OzyC7hnRhQMFTROvTAk9rMJr6weVWm6IUU0PTP7fjJcTDaevifbRN9T9FmgMkVGm8tMhZQUs6655xhoggQ8rFaHJDfgmoV4GnFKzeos4K5OyL/q3WOik7CQsSlfk9Pits8h8C9zYlrxvNZsoBkRqbrdcBPF2WV9L1GiWOF2SFnA8MsG+fGihT5b5ZLtgA+zfICklGv0cS7+LiYoIgZUEs9sxe/NnJbIvgmTdPwZnSw7/EJbDU/FELapgMbNyqzy/fG+6gQ3b7qWKxV05NTrOWO/WALTQk20A1r1ZWGrp0YnSNasxNXSALvF/WCpJBz9Pu5W6/pMtNPz4lpUrX7z6vuO+gNnNe8GMBdqyLqvAJyOk4aA75aGirLaULsjmQ/GU07WOvMwWHez1HATGySphv8qkATc5/4DN2yW5F2QJAd2c7mDplvLZ7DOEZvmVNN1QX1WaqYOiLXI1sbLch6+tp6BpzO5p0xCq4suxE7j3j5J33l9dhNvOOED89D0IiirpjPqIpFnt9UJFYYELtFENbfwQYGNLJsu/KcahyBUr/NLK91sJStColP7b48tOXtTToEq+2VxAg=
before_install:
  - |
    if test ! -f "$HOME/.local/bin/stack"
    then
      VERSION=1.6.5
      URL="https://github.com/commercialhaskell/stack/releases/download/v$VERSION/stack-$VERSION-$TRAVIS_OS_NAME-x86_64.tar.gz"
      cd /tmp
      curl --location "$URL" > stack.tar.gz
      gunzip stack.tar.gz
      tar --extract --file stack.tar --strip-components 1
      mkdir --parents "$HOME/.local/bin"
      mv stack "$HOME/.local/bin"
      cd -
    fi
  - stack --version
install:
  - stack setup
  - stack build --only-dependencies --test
script:
  - stack build --pedantic --test
  - stack sdist
after_success:
  - mkdir -p deploy
  - cp -v "$(stack path --dist-dir)/ratel-$TRAVIS_TAG.tar.gz" deploy/ratel.tgz
  - mkdir -p "$HOME/.stack/upload"
  - >-
    echo "{
    \"username\": \"$HACKAGE_USERNAME\",
    \"password\": \"$HACKAGE_PASSWORD\"
    }" > "$HOME/.stack/upload/credentials.json"
deploy:
  - skip_cleanup: true
    on: { tags: true }
    provider: releases
    api_key: { secure: nI+ZQpwERXKRuC06Qs22lAbA5LAo/kk9d9knmjqjvWXSjWge+ztGltTkXOpHYioZ6ty2uwM7bBcC7mDZURJNP0MH4HbJs9bJvh2Lk58QvOXuzj+eaLczkYED5sjrUdRI1F9QYnhMvLkwxQezdop/7Mm80IwIlC95VdZBKM/AKhtzO7xj0er8Ho7nUvNYSzves7sIOgsV136U3Jxiu25qZaJy4BF08LRPgE4fj9hiKQBPBZ01F48laGaW2IhteVuAp0j68v/tG0/TBQBcYrj43EeUTm/43RDrT4aoZKwnolh+30qANQ3Feo/bial2KnFIjZ4oGxDPbt5Pnr6L4QFhMkCcIkizMTge0ThAX/BlGhGMnLL1PYF0cQ8mUJOv10zVfDJrrliHA8XgqY0hLLmGeRmM3hhjO0MVtb//6KxElmmx1uUdPME42gKuUxGFxkyQQ/BWpafwUEh/PjnewWrQbZEgXzVpKxrns2B6GneyUPnBfF3Xey6zX/ZGBNdeSXwkXyIq4KguukEw0lN9lbNKQuD5IeqKaL+4wMjEQ0ZJJvyWfHnYFluVVfGxlJrdGa2teyw2CimPKjB1/RhZ7EE67WSZsPiOxjmiNQ1DTp7TlWrSe5WHWYa3Ekq4WNaXArKnS91CAezzTxLrbTzezfm8Drn1HKw7k7sTGgZjfOugVbY= }
    file: deploy/ratel.tgz
  - skip_cleanup: true
    on: { tags: true }
    provider: script
    script: stack upload .
