name: ratel
version: 1.0.9

category: Exceptions
description: Ratel notifies Honeybadger about exceptions.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/ratel
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Notify Honeybadger about exceptions.

dependencies:
  aeson: '>= 0.11.2 && < 0.12 || >= 1.0.2 && < 1.5'
  base: '>= 4.9.0 && < 4.14'
  bytestring: '>= 0.10.8 && < 0.11'
  case-insensitive: '>= 1.2.0 && < 1.3'
  containers: '>= 0.5.7 && < 0.7'
  http-client: '>= 0.4.31 && < 0.7'
  http-client-tls: '>= 0.2.4 && < 0.4'
  http-types: '>= 0.9.1 && < 0.13'
  text: '>= 1.2.2 && < 1.3'
  uuid: '>= 1.3.12 && < 1.4'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: impl(ghc >= 8.8.1)
    ghc-options: -Wno-missing-deriving-strategies

library:
  source-dirs: library

tests:
  test:
    dependencies:
      filepath: '>= 1.4.1 && < 1.5'
      hspec: '>= 2.2.3 && < 2.8'
      ratel: -any
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
